apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../image-defaulter
resources:
- ../../../kustomize/base/am-cdk
- ../../../kustomize/base/idm-cdk
- ../../../kustomize/overlay/amster-upload
- amster-files.yaml

patches:
  - path: am.yaml
  - path: idm.yaml
